- hosts: all
  become: yes
  user: ec2-user
  become_user: root
  become_method: sudo

  roles:
  - apache
  
  pre_tasks
  - name: Wait 300 seconds, but only start checking after 60 seconds
    wait_for_connection:
      delay: 60
      timeout: 300
